server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mxj-jay/tensquare_env_config.git

management:   # 暴露触发消息总线的地址
  endpoint:
    web:
      exposure:
        include: bus-refresh
